nyc_data:
  borough:
    0: "Unknown (N/A)"
    1: "Manhattan"
    2: "Bronx"
    3: "Brooklyn"
    4: "Queens"
    5: "Staten Island"
    6: "???"
  
  topic: "New York City - Hotel Properties Citywide"
  source: "data.cityofnewyork.us"

  labels:
    x_axis: "Borough"
    y_axis: "# of Properties"

  bldg_class:
    RH:
      type: "Hotel/Boatel"
      description: "Covers hotels and boatels. Almost all buildings in this class are in Manhattan. The highest concentration can be \
      found in Hudson Square, Lincoln Square, the Theatre District, Central Midtown and Turtle Bay."
    HB:
      type: "Boutique: 10-100 Rooms, W/Luxury Facilities, Themed, Stylish, W/Full Svc Accommodations"
      description: "Covers boutique luxury hotels. The majority of hotels in this class are in Manhattan (84%). Can find most of them \
      in Murray Hill, SoHo, Central Midtown, the Theatre District and NoMad, all in Manhattan."
    HH:
      type: "Hostels - Bed Rentals In Dormitory-Like Settings W/Shared Rooms & Bathrooms"
      description: "Covers hostels and other dormitory-like rentals. The majority of buildings in this class are in Manhattan (89%), \
      and they make up just 1% of all buildings in the H general class. Can find most of them in the Upper West Side, the Theatre \
      District, Chelsea, Manhattan Valley and NoLIta, all in Manhattan."
    HR: 
      type: "SRO - 1 Or 2 People Housed In Individual Rooms In Multiple Dwelling Affordable Housing"
      description: "Designates rental buildings offering single-room occupancy units designed for low-income residents. The majority \
      of buildings in this class are in Manhattan (63%), and 28% of them are in Brooklyn. These buildings make up 4% of all \
      buildings in the H general class. The neighborhoods where you can find the most HR class hotels are the Upper West Side, \
      Harlem, Lincoln Square and Chinatown in Manhattan, and Brighton Beach in Brooklyn."
    HS:
      type: "Extended Stay/Suite: Amenities Similar To Apt; Typically Charge Weekly Rates & Less Expensive Than Full-Service Hotel"
      description: "The HS building class covers extended-stay hotels and other types of rentals similar to apartments, but not luxury \
      or full-service hotels. Manhattan has most of the buildings in this class available in the city (93%), and Queens has 5%. The \
      neighborhoods where you can find the most HS class buildings are Lenox Hill, Turtle Bay, Sutton Place, Manhattan Valley and the \
      Upper West Side."
    H1:
      type: "Luxury Hotel"
      description: "Consists of luxury hotels that were built prior to 1960 and are exclusive to Manhattan. The Radisson Lexington and \
      The Carlyle are examples of hotels that fall under this category \\- they were the second and the third biggest hotel transactions \
      in 2011. These hotels can most frequently be encountered in Midtown/Midtown South, Turtle Bay/East Midtown, Murray Hill/Kips Bay, \
      the Upper East Side/Carnegie Hill and Gramercy."
    H2:
      type: "Full Service Hotel"
      description: "Comprises of luxury hotels that were built after 1960. Most of them are in Manhattan, but several can be also found \
      in Queens, Brooklyn and Staten Island. One such hotel, the New York Palace, represented the biggest hotel transaction in 2011. \
      They can be found in the biggest numbers in Midtown/Midtown South, SoHo/Tribeca/Civic Central/Little Italy, Battery Park \
      City/Lower Manhattan, Turtle Bay/East Midtown and Chinatown, all of which are in Manhattan."
    H3:
      type: "Limited Service; Many Affiliatred with National Chain"
      description: "Represented by the motels in New York City. Most of them are in Queens, the Bronx and Brooklyn, but there are a \
      few in Manhattan and Staten Island as well. Motels are most frequent in Elmhurst/Maspeth (Queens), East New York (Brooklyn), \
      Co-Op City (the Bronx), Eastchester / Edenwald / Baychester (the Bronx) and Clinton (Manhattan)."
    H4:
      type: "Motel"
      description: "Made of private clubs and luxury-type hotels. Almost all of them are located in Manhattan, \
      especially in Upper East Side/Carnegie Hill and Midtown/Midtown South."
    H5:
      type: "Hotel; Private Club, Luxury Type"
      description: "Made of private clubs and luxury-type hotels. Almost all of them are located in Manhattan, \
      especially in Upper East Side/Carnegie Hill and Midtown/Midtown South."
    H6:
      type: "Apartment Hotel"
      description: "Comprises of apartment hotels that are most often found in Manhattan, with a few in Brooklyn and the Bronx. \
      They can most frequently be found on the Upper West Side, but also in Turtle Bay/East Midtown, Midtown/Midtown South, \
      Lincoln Square and Clinton."
    H7:
      type: "Apartment Hotel - Cooperatively Owned"
      description: "Made up of hotels that are coop-owned. The units in these buildings are owned individually, but the buildings \
      themselves operate as hotels. There are only 3 of these buildings in New York City, all in Manhattan: 797 5th Avenue, \
      109 East 56th Street and 50 Gramercy Park North."
    H8:
      type: "Dormitory"
      description: "Dormitories in NYC - the vast majority of them can be found in Manhattan and Brooklyn. The neighborhoods where \
      they are the most numerous are West Village (Manhattan), Morningside Heights (Manhattan), East Village (Manhattan), \
      Brooklyn Heights (Brooklyn) and Murray Hill/Kips Bay (Manhattan)."
    H9:
      type: "Miscellaneous Hotel"
      description: "Various types of hotels that don’t fit into any of the other H-class buildings. They are actually the most \
      numerous, accounting for approximately 40% of the total number of hotels. They are most frequent in Manhattan (55%), \
      Queens (26%) and Brooklyn (12%). The neighborhoods where they can be found most often are the Upper West Side (Manhattan), \
      Hudson Yards/Chelsea/Flatiron/Union Square (Manhattan), Midtown/Midtown South (Manhattan), Queens Bridge/Ravenswood/Long \
      Island City North (Queens) and Clinton (Manhattan)."